#
# SPDX-FileCopyrightText: The LineageOS Project
# SPDX-License-Identifier: Apache-2.0
#

COMMON_PATH := device/samsung/s5e8825-common

# Architecture
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-2a-dotprod
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_VARIANT := cortex-a76

# Bluetooth
BOARD_HAVE_BLUETOOTH_SLSI := true

# Display
BOARD_USES_DISPLAY_COLOR_INTERFACE := true
BOARD_USES_VIRTUAL_DISPLAY := true
HWC_SUPPORT_COLOR_TRANSFORM := true
TARGET_USES_DISPLAY_RENDER_INTENTS := true

# Display - HDR
BOARD_LIBHDR_PLUGIN := //vendor/samsung/s5e8825-common:libhdr_plugin_exynos8825
BOARD_LIBHDR10P_META_PLUGIN := //vendor/samsung/s5e8825-common:libhdr10p_meta_plugin_default

# Graphics
TARGET_USES_VULKAN := true

# Kernel
BOARD_KERNEL_IMAGE_NAME := Image
TARGET_KERNEL_CONFIG := s5e8825_defconfig $(TARGET_DEVICE).config
TARGET_KERNEL_SOURCE := kernel/samsung/s5e8825

# Kernel - Modules
BOARD_VENDOR_RAMDISK_KERNEL_MODULES_LOAD := $(strip $(shell cat device/samsung/$(TARGET_DEVICE)/configs/kernel/modules.load))
BOARD_RECOVERY_RAMDISK_KERNEL_MODULES_LOAD := $(BOARD_VENDOR_RAMDISK_KERNEL_MODULES_LOAD)
BOOT_KERNEL_MODULES := $(BOARD_VENDOR_RAMDISK_KERNEL_MODULES_LOAD)
RECOVERY_KERNEL_MODULES := $(BOARD_RECOVERY_RAMDISK_KERNEL_MODULES_LOAD)
BOARD_VENDOR_RAMDISK_FRAGMENTS := dlkm
BOARD_VENDOR_RAMDISK_FRAGMENT.dlkm.KERNEL_MODULE_DIRS := top

# Partitions
BOARD_USES_METADATA_PARTITION := true
BOARD_ROOT_EXTRA_FOLDERS := efs

# Partitions - Dynamic
BOARD_GROUP_BASIC_PARTITION_LIST := system system_ext vendor vendor_dlkm product
BOARD_GROUP_BASIC_SIZE := 11739856896
BOARD_SUPER_PARTITION_SIZE := 11744051200
BOARD_SUPER_PARTITION_GROUPS := group_basic

# Partitions - Filesystem
BOARD_CACHEIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_PRODUCTIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_SYSTEMIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_SYSTEM_EXTIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := erofs
BOARD_VENDOR_DLKMIMAGE_FILE_SYSTEM_TYPE := erofs
TARGET_COPY_OUT_PRODUCT := product
TARGET_COPY_OUT_SYSTEM_EXT := system_ext
TARGET_COPY_OUT_VENDOR := vendor
TARGET_COPY_OUT_VENDOR_DLKM := vendor_dlkm
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true

# Partitions - GMS
-include vendor/lineage/config/BoardConfigReservedSize.mk

# Partitions - Kernel
BOARD_BOOTCONFIG := buildtime_bootconfig=enable
BOARD_BOOT_HEADER_VERSION := 4
BOARD_DTB_CFG := $(COMMON_PATH)/configs/kernel/dtb.cfg
BOARD_DTBO_CFG := device/samsung/$(TARGET_DEVICE)/configs/kernel/dtbo.cfg
BOARD_INCLUDE_DTB_IN_BOOTIMG := true
BOARD_KERNEL_SEPARATED_DTBO := true
BOARD_MKBOOTIMG_ARGS := --header_version $(BOARD_BOOT_HEADER_VERSION)
BOARD_RAMDISK_USE_LZ4 := true

# Partitions - Size
BOARD_BOOTIMAGE_PARTITION_SIZE := 67108864
BOARD_CACHEIMAGE_PARTITION_SIZE := 209715200
BOARD_DTBOIMG_PARTITION_SIZE := 8388608
BOARD_FLASH_BLOCK_SIZE := 4096
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 100663296
BOARD_VENDOR_BOOTIMAGE_PARTITION_SIZE := 33554432

# Platform
BOARD_VENDOR := samsung
TARGET_BOARD_PLATFORM := erd8825
TARGET_BOOTLOADER_BOARD_NAME := s5e8825
TARGET_SOC := s5e8825

# Platform - Linaro
include hardware/samsung_slsi-linaro/config/BoardConfig8825.mk

# Properties
TARGET_VENDOR_PROP += $(COMMON_PATH)/configs/props/vendor.prop

# Recovery
BOARD_INCLUDE_RECOVERY_DTBO := true
BOARD_RECOVERY_MKBOOTIMG_ARGS := --header_version 2
TARGET_RECOVERY_FSTAB_GENRULE := gen_fstab_s5e8825.recovery
TARGET_RECOVERY_PIXEL_FORMAT := RGBX_8888

# Releasetools - Extension
TARGET_RELEASETOOLS_EXTENSIONS := $(COMMON_PATH)

# Verified Boot
BOARD_AVB_ENABLE := true
BOARD_AVB_MAKE_VBMETA_IMAGE_ARGS := --flags 3
BOARD_AVB_RECOVERY_ALGORITHM := NONE
BOARD_AVB_RECOVERY_KEY_PATH := external/avb/test/data/testkey_rsa4096.pem
BOARD_AVB_RECOVERY_ROLLBACK_INDEX := 0
BOARD_AVB_RECOVERY_ROLLBACK_INDEX_LOCATION := 1

# VINTF
DEVICE_FRAMEWORK_COMPATIBILITY_MATRIX_FILE += hardware/samsung/vintf/samsung_framework_compatibility_matrix.xml
DEVICE_MANIFEST_FILE := $(COMMON_PATH)/configs/vintf/manifest.xml

# Wi-Fi
BOARD_WLAN_DEVICE := slsi
BOARD_WPA_SUPPLICANT_DRIVER := NL80211
BOARD_WPA_SUPPLICANT_PRIVATE_LIB := lib_driver_cmd_slsi
BOARD_HOSTAPD_DRIVER := NL80211
BOARD_HOSTAPD_PRIVATE_LIB := lib_driver_cmd_slsi
WIFI_HIDL_FEATURE_DUAL_INTERFACE := true
WIFI_HIDL_UNIFIED_SUPPLICANT_SERVICE_RC_ENTRY := true
WPA_SUPPLICANT_VERSION := VER_0_8_X
